### ISSUE TITLE
The activities button appears on the lock screen for some reason

### ISSUE THREAD

**Issue by lolomokakus** [zeten30/HideActivities#2]
Hello! I recently started using this extension, it works great except for that the Activities button now appears on my lock screen instead of in the top bar. It doesn't do anything when you click it, but it's definitely there. I'm using version 9 on Gnome 3.36 on Fedora 32.

**Comment by zeten30** [comment]
@lolomokakus Hi, can you please attach a screenshot?

**Comment by lolomokakus** [comment]
Sure, here you go:
![Skärmbild från 2020-06-24 21-02-31](https://user-images.githubusercontent.com/10581783/85616588-43dd9e80-b65e-11ea-9c55-a4361f6e8dc2.png)

**Comment by lolomokakus** [comment]
Also, I don't have any other extensions enabled.

**Comment by zeten30** [comment]
@lolomokakus can you please try to replace extension.js file with this https://github.com/zeten30/HideActivities/blob/fix-activities-on-lock/extension.js ? (in ~/.local/share/gnome-shell/extensions/Hide_Activities@shay.shayel.org/)

**Comment by zeten30** [comment]
![Screenshot from 2020-06-30 20-46-05](https://user-images.githubusercontent.com/1825873/86165931-4d5e7f00-bb14-11ea-80ed-3b315b41198a.png)
![Screenshot from 2020-06-30 20-46-33](https://user-images.githubusercontent.com/1825873/86165936-4df71580-bb14-11ea-995d-9f83b5108293.png)

**Comment by lolomokakus** [comment]
This worked, thanks!

**Comment by lolomokakus** [comment]
It does make the app menu not completely aligned with the edge of the menu bar though, I'll post a screenshot later

**Comment by lolomokakus** [comment]
Here you go. Before the fix the app menu was aligned with the edge:
![before](https://user-images.githubusercontent.com/10581783/86236359-3e221480-bb9a-11ea-82fa-96c08b58baa5.png)
After the fix it isn't quite aligned:
![after](https://user-images.githubusercontent.com/10581783/86236407-4da15d80-bb9a-11ea-909c-f27fdb3a749c.png)
Not a big problem obviously, but slightly irritating nonetheless.

**Comment by zeten30** [comment]
Actually I like the 'not aligned' more. It doesn't interfere with rounded corner.. But that's personal preference. 

It might be more gnome-shell style thing..

Are you ok with merging this fix?

**Comment by lolomokakus** [comment]
Yeah, of course. Thanks for your help!
