### ISSUE TITLE
Add a power off button to the Gnome activity bar.

### ISSUE THREAD

**Issue by Pecita** [zeten30/HideActivities#7]
Hello,

I hope that my slightly divergent question will not upset you.
I want to find a gnome extension that does only one thing: add a power off button to the activity bar.

It's easy to do in the docking station but I don't know how to do it in the activity bar. Would you be so kind as to give me some hints on how to do this ?

I'm sure I'm not the only one who wants this!

Best regards,
Philippe

**Comment by zeten30** [comment]
Hi @Pecita,

no problem at all:)

You've probably noticed the shift towards [QuickSettings](https://gjs.guide/extensions/topics/quick-settings.html). However, there's still an option to add a 'regular button/icon' on activity bar.

I'm not aware about any recent/maintained extensions adding a power-off button to activity bar, but you can find other extensions adding different buttons. Found this one (for example) - [Show-Desktop-Button - Github - line 196](https://github.com/amivaleo/Show-Desktop-Button/blob/master/extension.js#L196) / [Show-Desktop-Button on extentions.gnome.org](https://extensions.gnome.org/extension/1194/show-desktop-button/).

It should be easy to fork. Replace all the window functions (~stuff above the ^ referenced line) by a simple power off function and keeping things that adds button to activity bar and basic extension functions (enable/disable/init.. below the referenced line ^).

[Gnome extensions dev docs](https://gjs.guide/extensions/topics/popup-menu.html#menu-items) improved quite a lot over the years.

Cheers
Milan

**Comment by Pecita** [comment]
With this clear and concrete answer, it only remains to do it! I'll give it a try.
Thank you.

**Comment by Pecita** [comment]
To leave a trace to who would be interested, I allow myself to self answer after having followed the indications of Milan.

In a terminal
`$ gnome-extensions create --interactive`
Choose option 2, modify the generated script as follows, activate the extension and you're done!
```
28a29,30
> const _SystemActions = imports.misc.systemActions;
> const SystemActions = _SystemActions.getDefault();
35c37
<         super._init(0.0, _('My Shiny Indicator'));
>         super._init(0.0, _('True Power-Off Indicator'));
38c40
<             icon_name: 'face-smile-symbolic',
>             icon_name: 'system-shutdown-symbolic',
42c44
<         let item = new PopupMenu.PopupMenuItem(_('Show Notification'));
>         let item = new PopupMenu.PopupMenuItem(_('Power Off'));
44c46
<             Main.notify(_('Whatʼs up, folks?'));
>             SystemActions.activatePowerOff();
```

**Comment by Pecita** [comment]
Sorry, issue closed to be clean.
