### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by D3vil0p3r** [zeten30/HideActivities#8]
Hello @zeten30 
Will the extension support GNOME 45 that will be released in the third week of September?

**Comment by zeten30** [comment]
Hi @D3vil0p3r 

should be fixed by https://github.com/zeten30/HideActivities/commit/3b44e62b5d6c45a0813e9b310634c23bf0fdc46f

New extension version (only for GNOME 45) is now pending review.

**Comment by zeten30** [comment]
https://extensions.gnome.org/review/44420

**Comment by zeten30** [comment]
![image](https://github.com/zeten30/HideActivities/assets/1825873/d74990fa-286e-406f-9a48-fb38c1aa8d81)

Approved/reviewed. Closing this one. Thanks for reminder @D3vil0p3r

**Comment by D3vil0p3r** [comment]
Thank you very much @zeten30 I will wait for the stable GNOME 45 and then I will deploy your solution on [Athena OS](https://athenaos.org/).
